services:
  e621-bot-go:
    image: ghcr.io/bakatrouble/e621-bot-go:latest
    volumes:
      - "./cache:/cache"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      REDIS: redis://valkey:6379/0
      INTERVAL: 60s

  valkey:
    image: valkey/valkey:9-alpine
    volumes:
      - "./valkey:/data"
